fix

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -34,8 +34,10 @@ jobs:
         run: |
           npm run unit
           exit_code=$?
-          npm run upload-mochawesome
-          exit $exit_code
+          if [ $exit_code -ne 0 ]; then
+            echo "Unit Tests failed."
+            exit 1 # Exit with an error code to indicate failure
+          fi
 
   upload-mochawesome:
     name: Upload Mochawesome Report
@@ -85,8 +87,7 @@ jobs:
   build:
     name: User app
     runs-on: ubuntu-latest
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only run on push to main branch
-
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && failure() != true && needs.unit-test.result == 'success' # Only run on push to main branch if unit-test succeeds
     strategy: 
       matrix:
         node-version: [16.x]
